<?php
// $helper = $this->helper('Bluethink\Verify\Helper\Data');
// $values = $helper->getConfigValue();

$values=$block->getBlogs();

if($values==1):

?>

<div id="popup-modal">
<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $block->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                    <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Name')) ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="name" value="" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Email')) ?></span></label>
                            <div class="">
                                <input name="email" id="email" title="email" value="" class="input-text" type="text"
                                >
                            </div>
                        </div>
              
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <!-- <button type="submit" class="action submit primary" title="Save" id="submit_data"></button> -->
                </div>
            </div>
        </form>
     
    </div>
</div> 
</div>
<div id="successMessage"> </div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($,modal){
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Custom Form Popup',
                buttons: [{
                    text: $.mage.__('Submit'),
                    class: '',
                    click: function () {
                        // this.closeModal();
                        var name = $("#name").val();
				        var email = $("#email").val();
                        $.ajax({
                            url: "<?php echo $block->getUrl('verify/index/save') ?>", 
                            dataType:JSON,
                            data: {
						        name: name,
						        email: email,
					        },
                            cache: false,
                            success: function(data){
                                $(".row").html(JSON.stringify(data));
                              $("#addData").trigger('reset');


                            }
                    });
                }
                    // }
                }]
                // [{ 
                //     text: $.mage.__('Submit'),
                //     class: '',
                //     click: function () {
                //         var nickName = $("input[name='name']").val();
                //         var textReview = $("input[name='email']").val();
                //         var url = "<?php //echo $block->getUrl('test/index/save') ?>";
                //         jQuery.ajax({
                //         url: url,
                //         type: "POST",
                //         data: {nickname:name,textreview:email},
                //         showLoader: true,
                //         // this.closeModal();
                //     });
                // }
            //     }]
            };
            var popup = modal(options, $('#popup-modal'));
            $('#popup-modal').modal('openModal');

        //     $('#submit_data').on('click', function (){
        //     $("h3").text("Hello world!");
        //     var nickName = $("input[name='name']").val();
        //     var textReview = $("input[name='email']").val();
        //       jQuery.ajax({
        //         url: url,
        //         type: "POST",
        //         data: {nickname:name,textreview:email},
        //         showLoader: true,
        //     });
        // });
        }
    );
</script>
<?php endif; ?> 

